"""Render a campaign evidence package as a court-ready PDF.

The PDF is a presentation of the JSON package, not a second source of truth:
it carries the same SHA-256 computed over the canonical JSON, so a recipient
can re-hash the JSON and confirm the printed digest matches.

reportlab is optional — callers get None if it is not installed, and the JSON
endpoint keeps working.
"""
import io
import logging

logger = logging.getLogger(__name__)


def available() -> bool:
    try:
        import reportlab  # noqa: F401

        return True
    except ImportError:
        return False


def render(package: dict) -> bytes | None:
    """Return PDF bytes for an evidence package, or None if reportlab is absent."""
    if not available():
        logger.info("reportlab not installed; PDF export unavailable")
        return None

    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    styles = getSampleStyleSheet()
    mono = ParagraphStyle("mono", parent=styles["BodyText"], fontName="Courier",
                          fontSize=7.5, leading=9.5, alignment=TA_LEFT)
    small = ParagraphStyle("small", parent=styles["BodyText"], fontSize=8.5, leading=11)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=16 * mm, bottomMargin=16 * mm,
        title=package.get("reference", "Evidence Package"),
        author="Project Netra",
    )

    campaign = package.get("campaign", {})
    story = [
        Paragraph("Fraud Campaign Evidence Package", styles["Title"]),
        Paragraph(f"Reference <b>{package.get('reference','—')}</b>", styles["Normal"]),
        Spacer(1, 6 * mm),
    ]

    def table(rows, widths, header=True):
        t = Table(rows, colWidths=widths, repeatRows=1 if header else 0)
        style = [
            ("FONTSIZE", (0, 0), (-1, -1), 7.5),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#b8c2cc")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f6f8")]),
        ]
        if header:
            style += [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2a37")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        t.setStyle(TableStyle(style))
        return t

    # --- integrity block (the point of the document) ---------------------
    story += [
        Paragraph("Integrity", styles["Heading2"]),
        table([
            ["SHA-256 (canonical JSON)", Paragraph(package.get("integrity_sha256", "—"), mono)],
            ["Generated by", package.get("provenance", {}).get("generated_by", "—")],
            ["System", package.get("provenance", {}).get("system", "Project Netra")],
        ], [45 * mm, 125 * mm], header=False),
        Spacer(1, 3 * mm),
        Paragraph(
            "Recompute the digest over the canonical JSON (sorted keys, no whitespace) "
            "to verify this document has not been altered.", small),
        Spacer(1, 6 * mm),
    ]

    # --- campaign summary -------------------------------------------------
    story += [
        Paragraph("Campaign", styles["Heading2"]),
        table([
            ["Field", "Value"],
            ["Label", str(campaign.get("label", "—"))],
            ["Script family", str(campaign.get("script_family") or "—")],
            ["Risk level", f"{campaign.get('risk_level','—')} "
                           f"({campaign.get('max_risk_score','—')})"],
            ["Sessions", str(campaign.get("session_count", "—"))],
            ["Caller numbers", ", ".join(campaign.get("caller_numbers", [])) or "—"],
            ["Device fingerprints", str(len(campaign.get("device_hashes", [])))],
            ["Linked victim reports", str(campaign.get("linked_report_count", 0))],
            ["First activity", str(campaign.get("first_activity") or "—")],
            ["Last activity", str(campaign.get("last_activity") or "—")],
        ], [45 * mm, 125 * mm]),
        Spacer(1, 6 * mm),
    ]

    # --- call timeline ----------------------------------------------------
    calls = package.get("call_timeline", [])
    story += [Paragraph(f"Call timeline ({len(calls)})", styles["Heading2"])]
    if calls:
        rows = [["Started", "Caller", "Victim", "Ch.", "Min", "Spoofed"]]
        for c in calls[:40]:
            rows.append([
                str(c.get("started_at", ""))[:19], str(c.get("caller_number") or "—"),
                str(c.get("victim_contact") or "—"), str(c.get("channel", "")),
                str(c.get("duration_minutes") or "—"),
                "YES" if c.get("spoofed") else "no",
            ])
        story.append(table(rows, [34 * mm, 33 * mm, 33 * mm, 20 * mm, 15 * mm, 20 * mm]))
    else:
        story.append(Paragraph("No call records.", small))
    story += [Spacer(1, 6 * mm)]

    # --- sessions ---------------------------------------------------------
    sessions = package.get("sessions", [])
    story += [PageBreak(), Paragraph(f"Screened sessions ({len(sessions)})", styles["Heading2"])]
    if sessions:
        rows = [["Created", "Verdict", "Risk", "Agency", "Indicators"]]
        for s in sessions[:30]:
            rows.append([
                str(s.get("created_at", ""))[:19], str(s.get("verdict", "")),
                str(s.get("risk_score", "")), str(s.get("claimed_agency") or "—"),
                Paragraph("; ".join(s.get("indicators", [])[:3]) or "—", mono),
            ])
        story.append(table(rows, [30 * mm, 30 * mm, 14 * mm, 22 * mm, 74 * mm]))
    else:
        story.append(Paragraph("No sessions.", small))
    story += [Spacer(1, 6 * mm)]

    # --- mule accounts ----------------------------------------------------
    accounts = package.get("mule_accounts", [])
    story += [Paragraph(f"Linked accounts ({len(accounts)})", styles["Heading2"])]
    if accounts:
        rows = [["Bank", "IFSC", "Account", "Inflow (INR)", "Velocity", "KYC"]]
        for a in accounts[:30]:
            rows.append([
                str(a.get("bank") or "—"), str(a.get("ifsc") or "—"),
                str(a.get("account_number_masked") or "—"),
                f"{a.get('inflow_inr', 0):,}", f"{a.get('velocity_per_day', 0)}/day",
                "yes" if a.get("kyc_verified") else "NO",
            ])
        story.append(table(rows, [26 * mm, 30 * mm, 26 * mm, 34 * mm, 26 * mm, 18 * mm]))
    else:
        story.append(Paragraph("No linked accounts.", small))

    # --- provenance / disclaimer -----------------------------------------
    story += [
        Spacer(1, 6 * mm),
        Paragraph("Provenance", styles["Heading2"]),
        Paragraph(package.get("provenance", {}).get("methodology", "—"), small),
        Spacer(1, 3 * mm),
        Paragraph("Source tables: "
                  + ", ".join(package.get("provenance", {}).get("source_tables", [])), small),
        Spacer(1, 5 * mm),
        Paragraph(f"<i>{package.get('disclaimer', '')}</i>", small),
    ]

    doc.build(story)
    return buf.getvalue()
